### ISSUE TITLE
NOT_AN_ISSUE (feedback)

### ISSUE THREAD

**Issue by DinCraft** [Chronos-DX/Nucleardustry#5]
I don't know how to leave comment so I am leaving it here. This mod is very cool because I wanted to play with something connected with nuclear physics. And also I like when people use science as a source of ideas for mods. +1 star. Improve your mod and it will become popular.

**Comment by Chrono-Heritage** [comment]
Thanks for playing with this mod! I make this mod because of a mod from Minecraft called Nuclearcraft, I really like this mod so when my friend told me that I can make a mod for Mindustry, I decided to use nuclear physics as the topic. I also have many thinkings about this mod (e.g. multiblock structure for reactors, radioactivity for environment, etc.), but i still learning how to do these.

**Comment by DinCraft** [comment]
Wow! I tryed to make mod about nuclear things because i also played with nuclearcraft. I made private repository NuclearCraft a few month ago but i stopped developing because it takes a lot of time.

**Comment by DinCraft** [comment]
Lets do it together
